from typing import Protocol


class BundleStore(Protocol):
    def list_markdown(self, rel_dir: str) -> list[str]: ...

    def list_subdirs(self, rel_dir: str) -> list[str]: ...

    def read_text(self, rel_path: str) -> str: ...

    def write_text(self, rel_dir: str, filename: str, content: str) -> None: ...

    def walk(self, rel_dir: str) -> list[str]: ...

    def exists(self, rel_path: str) -> bool: ...